import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    // alignItems: 'center',
    backgroundColor: '#fff',
  },
  sessionsContainer: {
    flex: 1,
    justifyContent: 'center',
    // alignItems: 'center',
    backgroundColor: '#fff',
  },
  sessionsHeaderContainer: {
    marginTop: 16,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
    textAlign: 'center',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    padding: 10,
    marginHorizontal: 10,
  },
  searchBar: {
    flex: 1,
    height: 40,
    fontSize: 16,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 20,
    paddingHorizontal: 15,
    paddingVertical: 10,
    paddingRight: 35, // Make room for clear icon
    position: 'relative', // For absolute positioning of clear icon
  },
  clearIcon: {
    position: 'absolute',
    right: 8,
    //top: '50%',
    transform: [{ translateY: -10 }], // Half of icon size to center vertically
  },
  message: {
    textAlign: 'center',
    paddingBottom: 10,
  },
  camera: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
  },
  text: {
    fontSize: 20,
    color: '#000',
  },
  showUploadText: {
    fontSize: 16,
    color: '#000',
  },
  buttonContainer: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: 'transparent',
    margin: 64,
  },
  button: {
    flex: 1,
    alignSelf: 'flex-end',
    alignItems: 'center',
  },
  bottomBar: {
    backgroundColor: 'black',
    height: 100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  captureButton: {
    width: 70,
    height: 70,
    backgroundColor: 'white',
    borderRadius: 35,
    borderWidth: 5,
    borderColor: 'black',
  },
  captureButtonOuter: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 2,
    borderColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  captureButtonInner: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: '#fff',
  },
  torchButton: {
    position: 'absolute',
    right: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  swapFacing: {
    position: 'absolute',
    left: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  topBar: {
    display: 'flex',
    paddingHorizontal: 20,
    paddingVertical: 10,
    backgroundColor: '#f9f9f9',
  },
  profileText: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  submitButton: {
    flex: 0.25,
    backgroundColor: '#2F4858',
    paddingHorizontal: 15,
    paddingVertical: 5,
    borderRadius: 5,
    paddingBottom: 10,
  },
  viewImagesButton: {
    backgroundColor: '#E0EFFF',
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderRadius: 5,
    marginRight: 10,
    borderColor: '#33658A',
    borderStyle: 'solid',
    borderWidth: 1,
  },
  submitButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    alignSelf: 'center',
    justifyContent: 'center',
    textAlign: 'center',
  },
  viewImagesButtonText: {
    color: 'black',
    fontWeight: 'bold',
    alignSelf: 'center',
  },
  sessionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 10,
  },
  chevronIcon: {
    marginRight: 10, // Add space between the chevron and the card's edge
  },

  sessionDescription: {
    marginBottom: 10,
    fontSize: 14,
    color: '#333',
  },
  icon: {
    marginRight: 10,
  },
  patientProfile: {
    fontSize: 16,
    color: '#333',
    flex: 1,
  },
  sessionInput: {
    flex: 2,
    height: 35,
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 5,
    paddingHorizontal: 8,
    marginRight: 10,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
  },
  profileRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    marginBottom: 5,
  },
  inputContainer: {
    flexDirection: 'row',
  },
  input: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#ccc',
    padding: 10,
    borderRadius: 5,
    marginRight: 10,
  },
  overlayImage: {
    opacity: 0.5, // Adjust opacity for translucency
    width: '100%',
    height: '90%',
    shadowColor: 'black',
    backgroundColor: '#D3D3D3',
    tintColor: 'black',
  },
  bodyPartSelector: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 10,
    backgroundColor: 'transparent',
  },
  bodyPartButton: {
    padding: 10,
    marginHorizontal: 5,
    backgroundColor: '#f0f0f0',
    borderRadius: 5,
  },
  selectedBodyPart: {
    backgroundColor: '#ADD8E6', // Light blue highlight
  },
  bodyPartText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
  },
  checkbox: {
    marginVertical: 8,
    backgroundColor: 'transparent',
    paddingRight: 8,
    marginRight: 8,
  },
  filters: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 20,
  },
  filterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#E0E0E0',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
  },
  filterButtonSelected: {
    backgroundColor: '#2F4858',
  },
  filterText: {
    color: '#555',
    fontSize: 14,
    fontWeight: '500',
  },
  filterTextSelected: {
    color: '#fff',
  },
  checkmark: {
    marginRight: 4,
  },
  checkboxContainer: {
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 5,
  },
  sessionsText: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 16,
    marginHorizontal: 12,
    textAlign: 'center',
  },
  list: {
    paddingBottom: 16,
  },
  sessionCard: {
    backgroundColor: '#E0EFFF',
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    marginHorizontal: 12,
    borderWidth: 1,
  },
  expandedCard: {
    backgroundColor: 'transparent',
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    marginHorizontal: 12,
    borderWidth: 1,
  },
  sessionTitle: {
    fontWeight: 'bold',
    fontSize: 16,
    flex: 1,
  },
  sessionDetails: {
    marginTop: 8,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    padding: 20,
  },
  modalContent: {
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 20,
    width: '90%',
    maxHeight: '80%',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  closeButton: {
    alignSelf: 'flex-end',
    padding: 10,
    position: 'absolute',
    right: 10,
    top: 10,
    zIndex: 1,
  },
  carouselContainer: {
    width: '100%',
    height: 300,
    marginTop: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  carouselImage: {
    width: '100%',
    height: '90%',
    resizeMode: 'contain',
    borderRadius: 100
  },
  sessionInfo: {
    width: '100%',
    // padding: 10,
    // marginTop: 10,
  },
  // sessionTitle: {
  //   fontSize: 18,
  //   fontWeight: 'bold',
  //   marginBottom: 10,
  // },
  // sessionDescription: {
  //   fontSize: 14,
  //   color: '#666',
  // },
  actions: {
    flexDirection: 'row',
    marginTop: 8,
  },
  popupOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  popupContainer: {
    backgroundColor: 'white',
    borderRadius: 15,
    padding: 20,
    alignItems: 'center',
    width: '80%',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  popupTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginVertical: 10,
    textAlign: 'center',
  },
  popupMessage: {
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 20,
    color: '#666',
  },
  popupButton: {
    backgroundColor: '#2F4858',
    paddingHorizontal: 30,
    paddingVertical: 10,
    borderRadius: 8,
  },
  popupButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
  },
  carouselButton: {
    position: 'absolute',
    top: '50%',
    left: 10,
    zIndex: 2,
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: 20,
    // padding: 8,
    transform: [{ translateY: -20 }],
  },
  carouselButtonRight: {
    left: undefined,
    right: 5,
  },
  carouselTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    paddingHorizontal: 10,
  },
  profileCard: {
    backgroundColor: 'white',
    padding: 16,
    marginBottom: 12,
    marginHorizontal: 12,
  },
  profileDetails: {
    marginLeft: 48,
  },
  profileDetailsText: {
    color: 'gray',
  },
  createProfileButton: {
    flex: 1,
    backgroundColor: '#2F4858',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 5,
    justifyContent: 'center',
  },
  profileDetailsContainer: {
    flex: 1,
    // backgroundColor: '#f5f5f5',
    alignItems: 'center',
    paddingVertical: 20,
    minHeight: 800,
  },
  profileDetailsTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#000',
    textAlign: 'center',
    marginBottom: 20,
  },
  profileDetailsWrapper: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: 'lightgray',
    // alignItems: 'center',
    borderRadius: 10,
    padding: 30,
    marginVertical: 10,
    width: '80%',
    height: '60%',
  },
  profileTextWrapper: {
    paddingVertical: 10,
  },
  profileDetailsSubtitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#000',
    marginBottom: 5,
  },
  profileDetailsData: {
    fontSize: 14,
    color: '#757575',
  },
  viewPhotoSessionButton: {
    flex: 1.5,
    backgroundColor: '#2F4858',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  viewPhotoSessionButtonContainer: {
    flex: 1,
    flexDirection: 'row',
    paddingVertical: 20,
    paddingHorizontal: 16,
    alignItems: 'center', // Center the button horizontally
  },
  deleteButton: {
    flex: 1,
    backgroundColor: '#ff4444',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  deleteButtonText: {
    color: 'white',
    marginLeft: 8,
    fontSize: 16,
    fontWeight: '500',
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.6)',
  },
  modalContainerProgress: {
    width: 300,
    padding: 30,
    backgroundColor: 'white',
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingText: {
    fontSize: 18,
    color: 'black',
    marginTop: 20,
    fontWeight: '500',
    textAlign: 'center',
  },
  okButton: {
    marginTop: 30,
    backgroundColor: '#4A90E2',
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 10,
  },
  okButtonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  bulletPoint: {
    fontSize: 16,
    color: "#333",
    marginBottom: 5,
  },
  popupText: {
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 10,
  },
  popupContainerStep: {
    position: 'absolute',
    top: '40%',
    left: '10%',
    right: '10%',
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 10,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 5,
  },
  startSessionContainer: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: [{ translateX: -50 }, { translateY: -150 }],
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: 'transparent',
    zIndex: 999,
  },
  startSessionButton: {
    backgroundColor: '#007AFF',
    padding: 15,
    borderRadius: 5,
  },
  startSessionButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  sessionTitleText: {
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    marginVertical: 10,
  },
});

export default styles;
